### ISSUE TITLE
Create a FFT function

### ISSUE THREAD

**Issue by cwlowder** [AlmasTalkingDogs/Doge#14]
FFT, or [Fast Fourier Transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform), will be very important for data processing. Let's create a new directory in the base of our repo called `training` or something like that. Inside we'll put all the functions for training. Create a `fourier.py` file and then write a function that we can import from other files that takes in an array of integers, or floats? and does FFT on it. There's already an implementation of this in `analysis/train_classifier.py`, so it may just involve **copying over this function**, however please try to learn a bit about fft while you do so. This is a great first project for those interested in ML.

**Comment by cwlowder** [comment]
@asdhruv2 How is this coming along? Need any help?

**Comment by asdhruv2** [comment]
Hi, I am currently reading more about FFT and it uses so I can implement it by today.
